//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auction.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class auction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public auction()
        {
            this.orders = new HashSet<order>();
        }
    
        public int id { get; set; }
        public Nullable<int> product_id { get; set; }
        public double bid_price { get; set; }
        public System.DateTime auction_datetime { get; set; }
        public Nullable<int> bidstatus_id { get; set; }
        public Nullable<int> reason_id { get; set; }
        public Nullable<int> customer_id { get; set; }
    
        public virtual bid_status bid_status { get; set; }
        public virtual customer customer { get; set; }
        public virtual product product { get; set; }
        public virtual bid_status_reason bid_status_reason { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> orders { get; set; }
    }
}
