//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auction.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AuctionSystemEntities : DbContext
    {
        public AuctionSystemEntities()
            : base("name=AuctionSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<auction> auctions { get; set; }
        public virtual DbSet<bid_status> bid_status { get; set; }
        public virtual DbSet<bid_status_reason> bid_status_reason { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<customer_address> customer_address { get; set; }
        public virtual DbSet<customer_payment> customer_payment { get; set; }
        public virtual DbSet<customer_status> customer_status { get; set; }
        public virtual DbSet<order> orders { get; set; }
        public virtual DbSet<payment_method> payment_method { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<product_type> product_type { get; set; }
        public virtual DbSet<status_reason> status_reason { get; set; }
    }
}
