//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auction.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int id { get; set; }
        public int order_amount { get; set; }
        public System.DateTime order_datetime { get; set; }
        public Nullable<int> customer_payment_id { get; set; }
        public Nullable<int> auction_id { get; set; }
        public Nullable<int> customer_id { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<int> status_reason_id { get; set; }
    
        public virtual auction auction { get; set; }
        public virtual customer customer { get; set; }
        public virtual customer_payment customer_payment { get; set; }
        public virtual customer_status customer_status { get; set; }
        public virtual status_reason status_reason { get; set; }
    }
}
