//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auction.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.auctions = new HashSet<auction>();
        }
    
        public int id { get; set; }
        public Nullable<int> product_type_id { get; set; }
        public string product_Name { get; set; }
        public double product_bid_price { get; set; }
        public System.DateTime product_bid_time { get; set; }
        public Nullable<int> customer_id { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<int> status_reason_id { get; set; }
        public string product_description { get; set; }
        public double max_price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<auction> auctions { get; set; }
        public virtual customer customer { get; set; }
        public virtual customer_status customer_status { get; set; }
        public virtual product_type product_type { get; set; }
        public virtual status_reason status_reason { get; set; }
    }
}
